services:
  php83:
    build:
      context: .
      dockerfile: docker/php83/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - composer-cache:/tmp/composer-cache
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache

  php81:
    build:
      context: .
      dockerfile: docker/php81/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - composer-cache:/tmp/composer-cache
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache

volumes:
  composer-cache:
